---
services:
  redis:
      image: "docker.io/library/redis:latest"
      ports:
        - "6379:6379"
      restart: always
      
  restai:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - '9000:9000'
    volumes:
    - '.:/app'
    - '.cache:/home/user/.cache'
    environment:
      LOG_LEVEL: DEBUG
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RESTAI_DEV: ${RESTAI_DEV}
