---
version: '3'

services:
  restai:
    image: restai
    restart: always
    ports:
    - '9000:9000'
    volumes:
    - '.:/app'
    - '.cache:/home/user/.cache'
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
