[tool.poetry]
name = "restai"
version = "5.0.2"
description = "RESTAI, so many 'A's and 'I's, so little time..."
authors = ["Pedro Dias <petermdias@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
openai = "^1.50.2"
fastapi = "^0.111.1"
langchain = "^0.2.10"
uvicorn = "*"
python-multipart = "*"
python-dotenv = "*"
"pdfminer.six" = "*"
unstructured = "*"
pydantic = "^2.9.2"
pygpt4all = "*"
llama-cpp-python = "*"
sentence_transformers = "^2.7.0"
tiktoken = "*"
python-pptx = "*"
bs4 = "*"
selenium = "*"
yake = "^0.4.8"
passlib = "^1.7.4"
SQLAlchemy = "^2.0.35"
jq = "^1.8.0"
redis = "^5.1.0"
openpyxl = "^3.1.5"
google-cloud-aiplatform = "^1.68.0"
pymysql = "^1.1.1"
unidecode = "^1.3.8"
httpx = "0.27.0"
exceptiongroup = "^1.2.2"
wheel = "^0.42.0"
pyjwt = "^2.9.0"
langchain-community = "^0.2.9"
langchain-openai = "^0.1.17"
pypdf = "^4.3.1"
ollama = "^0.3.0"
opencv-python = "^4.10.0.84"
ip-adapter = "^0.1.0"
ilock = "^1.0.3"
docx2txt = "^0.8"
llama-index-core = "^0.11.15"
llama-index-embeddings-langchain = "^0.2.1"
llama-index-vector-stores-redis = "^0.3.4"
llama-index-vector-stores-chroma = "^0.2.0"
redisvl = "^0.3.4"
chromadb = "^0.5.11"
llama-index-llms-openai = "^0.2.9"
einops = "^0.8.0"
llama-index-llms-ollama = "^0.3.4"
llama-index-postprocessor-colbert-rerank = "^0.2.1"
llama-index-llms-groq = "^0.2.0"
llama-index-embeddings-openai = "^0.2.5"
llama-index-readers-file = "^0.2.2"
deepeval = "^1.3.2"
llama-index-llms-anthropic = "^0.3.4"
llama-index-llms-litellm = "^0.2.1"
psycopg2 = "^2.9.9"
llama-index-vector-stores-pinecone = "^0.2.1"
sentry-sdk = {extras = ["fastapi"], version = "^1.45.1"}
llama-index-llms-gemini = "^0.3.5"
google-generativeai = "^0.5.4"
llama-index-llms-vertex = "^0.3.6"
llama-index-llms-azure-openai = "^0.2.1"
duckduckgo-search = "^6.2.13"
wikipedia = "^1.4.0"
llama-index-storage-chat-store-redis = "^0.3.2"
pandas = "^2.2.3"
llama-index-llms-vllm = "^0.2.0"
llama-index-multi-modal-llms-ollama = "^0.3.3"
llama-index-llms-openai-like = "^0.2.0"

[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
transformers = "^4.45.1"
insightface = "^0.7.3"
xformers = "^0.0.28.post2"
optimum = "1.13.1"
accelerate = "^1.0.1"
bitsandbytes = "^0.44.1"
diffusers = "0.31.0"
torch = "^2.5.0"
flash_attn = "^2.6.3"
auto-gptq = "^0.6.0"

[tool.poetry.dev-dependencies]
pylint = "3.0.2"
autopep8 = "2.0.4"
debugpy = "^1.8.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
