[tool.poetry]
name = "restai"
version = "4.0.0"
description = "RESTAI, so many 'A's and 'I's, so little time..."
authors = ["Pedro Dias <petermdias@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
openai = "^1.30.0"
fastapi = "^0.109.0"
langchain = "^0.1.20"
uvicorn = "*"
python-multipart = "*"
python-dotenv = "*"
"pdfminer.six" = "*"
unstructured = "*"
pydantic = "^2.5.0"
pygpt4all = "*"
llama-cpp-python = "*"
sentence_transformers = "^2.3.1"
tiktoken = "*"
python-pptx = "*"
bs4 = "*"
selenium = "*"
yake = "^0.4.8"
passlib = "^1.7.4"
SQLAlchemy = "^2.0.25"
jq = "^1.6.0"
transformers = "^4.37.2"
accelerate = "^0.26.1"
optimum = "1.13.1"
redis = "^5.0.1"
openpyxl = "^3.1.2"
google-cloud-aiplatform = "^1.51.0"
bitsandbytes = "^0.42.0"
diffusers = "0.25.1"
pymysql = "^1.1.0"
unidecode = "^1.3.7"
httpx = "0.25.2"
exceptiongroup = "^1.2.0"
wheel = "^0.42.0"
pyjwt = "^2.8.0"
langchain-community = "^0.0.38"
langchain-openai = "^0.1.6"
pypdf = "^4.0.1"
ollama = "^0.1.6"
insightface = "^0.7.3"
opencv-python = "^4.9.0.80"
ip-adapter = "^0.1.0"
ilock = "^1.0.3"
docx2txt = "^0.8"
llama-index-core = "^0.10.36"
llama-index-embeddings-langchain = "^0.1.2"
llama-index-vector-stores-redis = "^0.2.0"
llama-index-vector-stores-chroma = "^0.1.8"
redisvl = "^0.1.3"
chromadb = "^0.4.22"
llama-index-llms-openai = "^0.1.19"
einops = "^0.7.0"
llama-index-llms-ollama = "^0.1.3"
llama-index-postprocessor-colbert-rerank = "^0.1.2"
llama-index-llms-groq = "^0.1.3"
llama-index-embeddings-openai = "^0.1.9"
llama-index-readers-file = "^0.1.22"
deepeval = "^0.21.0"
llama-index-llms-anthropic = "^0.1.11"
llama-index-llms-litellm = "^0.1.4"
psycopg2 = "^2.9.9"
llama-index-vector-stores-pinecone = "^0.1.7"
sentry-sdk = {extras = ["fastapi"], version = "^1.45.0"}
xformers = "^0.0.26.post1"
llama-index-llms-gemini = "^0.1.8"
google-generativeai = "^0.4.1"
llama-index-llms-vertex = "^0.1.5"
llama-index-llms-azure-openai = "^0.1.8"

[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
torch = "^2.2.0"
flash_attn = "^2.5.2"
auto-gptq = "^0.6.0"

[tool.poetry.dev-dependencies]
pylint = "3.0.2"
autopep8 = "2.0.4"
debugpy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
