[tool.poetry]
name = "restai"
version = "4.0.0"
description = "RESTAI, so many 'A's and 'I's, so little time..."
authors = ["Pedro Dias <petermdias@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.6.1"
fastapi = "*"
langchain = "*"
uvicorn = "*"
python-multipart = "*"
python-dotenv = "*"
"pdfminer.six" = "*"
unstructured = "*"
pydantic = "^2.5.0"
pygpt4all = "*"
llama-cpp-python = "*"
sentence_transformers = "*"
chromadb = "*"
tiktoken = "*"
python-pptx = "*"
bs4 = "*"
selenium = "*"
yake = "*"
GPUtil = "*"
psutil = "*"
passlib = "*"
SQLAlchemy = "*"
jq = "*"
transformers = "4.36.2"
accelerate = "0.24.1"
optimum = "1.13.1"
redis = "*"
redisvl = "*"
openpyxl = "*"
google-cloud-aiplatform = "*"
bitsandbytes = "*"
flash_attn = { version = "*", optional = true }
diffusers = "*"
torch = { version = "*", optional = true }
pymysql = "^1.1.0"
unidecode = "^1.3.7"
httpx = "0.25.1"
llama-index = "^0.9.24"
exceptiongroup = "^1.2.0"
wheel = "^0.42.0"
auto-gptq = { version = "*", optional = true }
pyjwt = "^2.8.0"

[tool.poetry.dev-dependencies]
pylint = "3.0.2"
autopep8 = "2.0.4"
debugpy = "^1.8.0"

[tool.poetry.extras]
gpu = ["torch", "auto-gptq", "flash_attn"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
