[tool.poetry]
name = "restai"
version = "4.0.0"
description = "RESTAI, so many 'A's and 'I's, so little time..."
authors = ["Pedro Dias <petermdias@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.10.0"
fastapi = "^0.109.0"
langchain = "^0.1.4"
uvicorn = "*"
python-multipart = "*"
python-dotenv = "*"
"pdfminer.six" = "*"
unstructured = "*"
pydantic = "^2.5.0"
pygpt4all = "*"
llama-cpp-python = "*"
sentence_transformers = "^2.3.1"
chromadb = "*"
tiktoken = "*"
python-pptx = "*"
bs4 = "*"
selenium = "*"
yake = "^0.4.8"
passlib = "^1.7.4"
SQLAlchemy = "^2.0.25"
jq = "^1.6.0"
transformers = "^4.37.2"
accelerate = "^0.26.1"
optimum = "1.13.1"
redis = "^5.0.1"
redisvl = "*"
openpyxl = "^3.1.2"
google-cloud-aiplatform = "*"
bitsandbytes = "^0.42.0"
diffusers = "0.25.1"
pymysql = "^1.1.0"
unidecode = "^1.3.7"
httpx = "0.25.1"
llama-index = "^0.9.40"
exceptiongroup = "^1.2.0"
wheel = "^0.42.0"
pyjwt = "^2.8.0"
langchain-community = "^0.0.16"
langchain-openai = "^0.0.5"
pypdf = "^4.0.1"

[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
torch = "^2.2.0"
flash_attn = "^2.5.2"
auto-gptq = "^0.6.0"

[tool.poetry.dev-dependencies]
pylint = "3.0.2"
autopep8 = "2.0.4"
debugpy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
